# Generated by Django 5.0.6 on 2024-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewcont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_pers', models.CharField(max_length=10, verbose_name='review perspective')),
                ('review_dir', models.CharField(max_length=100, verbose_name='review direction')),
            ],
        ),
    ]
