# Generated by Django 5.0.6 on 2024-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewAIapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_cont', models.CharField(max_length=200, verbose_name='review content')),
            ],
        ),
    ]
